services:
  db:
    container_name: "postgres"
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "4211:5432"
  gh:
    container_name: "gitstub"
    build:
      context: .devcontainer/gitstub/
    environment:
      DEBUG: "fauxauth:*"
      # noinspection JsonSchemaCompliance
      USERS: >
        [
          {
            "gitHubId": 123,
            "gitHubLogin": "cyf-admin",
            "name": "Cyf Admin",
            "publicEmails": ["admin@codeyourfuture.io"]
          },
          {
            "gitHubId": 456,
            "gitHubLogin": "discreet-volunteer",
            "privateEmails": ["shh@example.com"]
          }
        ]
    init: true
    ports:
      - "4212:4212"
