name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: docker compose up --detach
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run migration -- up
      - run: npm run lint
      - run: npm run test -- --coverage
        env:
          FORCE_COLOR: true
      - run: npm run e2e
        env:
          CYPRESS_VIDEO: true
      - run: docker compose down
        if: always()
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          if-no-files-found: ignore
          name: cypress-outputs
          path: |
            e2e/screenshots/
            e2e/videos/
  deploy:
    uses: "./.github/workflows/deploy.yml"
    if: github.ref == 'refs/heads/main'
    needs: build
    with:
      environment: heroku
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
